pub type Register = u8;
pub type Literal = u8;
pub type Label = String;

#[derive(PartialEq)]
pub enum Comparison {
    None,
    Equal,
    NotEqual,
    Greater,
    Less,
}

pub enum Node {
    Move(Register, Register),
    Add(Register, Register),
    Addc(Register, Register),
    Sub(Register, Register),
    And(Register, Register),
    Or(Register, Register),
    Xor(Register, Register),
    Cmp(Register, Register),
    Not(Register),
    Neg(Register),
    Inc(Register),
    Dec(Register),
    Shr(Register),
    Shla(Register),
    Shra(Register),
    Rol(Register),
    St(Register, Register),
    Ld(Register, Register),
    Push(Register),
    Pop(Register),
    Ldsa(Register, Literal),
    Addsp(Register, Literal),
    Setsp(Register, Literal),
    Pushall,
    Popall,
    Ldi(Register, Literal),
    Halt,
    Wait,
    Jsr,
    Rts,
    Ioi,
    Rti,
    Crc,
    Osix,
    Rand,
    BeqBz(Label),
    BneBnz(Label),
    BhsBcs(Label),
    BloBcc(Label),
    Bmi(Label),
    Bpl(Label),
    Bvs(Label),
    Bvc(Label),
    Bhi(Label),
    Bls(Label),
    Bge(Label),
    Blt(Label),
    Bgt(Label),
    Ble(Label),
    Br(Label),
    Nop(Label),
    Ldc(Register, Register),
}
